openapi: 3.0.0
info:
  title: resource-access-service
  version: v0
servers:
- url: /
tags:
- name: Access
  description: APIs tou check the resources a user have access to
paths:
  /api/resource/access/{data_type}/{user_id}:
    get:
      tags:
      - Access
      summary: Gets resource user has access to
      description: Returns list of ids of DataType user has access to
      operationId: get_resource_access_for_user
      parameters:
      - name: data_type
        in: path
        description: The data type ex book.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - book
          - room
      - name: user_id
        in: path
        description: The user id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceAccess'
        "404":
          description: User id does not exists
        "422":
          description: DataType does not exists
        "500":
          description: Something failed in the server
      x-openapi-router-controller: swagger_server.controllers.access_controller
    post:
      tags:
      - Access
      summary: Gives user access to a resource
      description: Adds a resource id to user access list
      operationId: add_resource_access_for_user
      parameters:
      - name: data_type
        in: path
        description: The data type ex book.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - book
          - room
      - name: user_id
        in: path
        description: The user id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: The resource id.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceRef'
        required: true
      responses:
        "200":
          description: Success
        "404":
          description: User id or resource id does not exists
        "422":
          description: DataType does not exists
        "500":
          description: Something failed in the server
      x-openapi-router-controller: swagger_server.controllers.access_controller
components:
  schemas:
    ResourceAccess:
      type: object
      properties:
        count:
          type: integer
        data:
          type: array
          items:
            type: string
      description: List of resource ids user has access to
      example:
        data:
        - data
        - data
        count: 0
    ResourceRef:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
      description: List of ids to give user access to

